### PR TITLE
[AS] made description unique in application dev

### PR DESCRIPTION
**Pull request by asamrae2y**

### CODE REVIEW

**Comment by asamrae2y** [comment]
we need it unique for the dev profile, doesn't work if you just change it in application.yml

**Comment by pandemicGander** [comment]
we need it unique for all profiles

**Comment by pandemicGander** [comment]
it should work if you change it on application.yml, it works for me

**Comment by rmcotton** [comment]
we have this now on https://github.com/e2y/adyen-mirakl/pull/27

**Pull request closed without merging**
